name: Scheduled Download

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Download file
        run: |
          curl -LOJ https://github.com/chenditc/investment_data/releases/download/2023-10-21/qlib_bin.tar.gz
          git add qlib_bin.tar.gz
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}
          git commit -m "Auto-download qlib_bin.tar.gz"
          git push
